[package]
name = "lottery-bin"
version = "0.1.0"
authors = ["fteychene <francois.teychene@gmail.com>"]

[dependencies]
error-chain = "0.11.0"
rocket = "0.3.6"
rocket_codegen = "0.3.6"
frunk = "0.1.34"
lottery-eventbrite = { path = "../eventbrite"}
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[dependencies.rocket_contrib]
version = "0.3.6"
features = ["json"]

[[bin]]
name = "lottery"